language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
# command to install dependencies
install:
  - pip install python-coveralls
  - python setup.py install 

# command to run tests
script:
    - coverage run setup.py test
#    - nosetests --with-coverage --cover-package=groio tests/test_groio.py
after_success:
    - coveralls
